Separate workflow in 2 files

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -1,16 +1,67 @@
-name: CI/CD Pipeline
+name: CI/CD Pipeline for pull request on master branch
 
 on:
-  push:
-    branches:
-      - develop
   pull_request:
     types: [ closed ]
     branches:
       - master
 
 jobs:
-  versioning:
+  label_check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v4
+
+      - name: Verify mandatory labels
+        id: label-check
+        run: |
+          MANDATORY_LABELS=("release:major" "release:minor" "release:patch")
+          
+          PR_LABELS=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
+          
+          for label in "${MANDATORY_LABELS[@]}"; do
+            if echo "$PR_LABELS" | grep -q "$label"; then
+              echo "Mandatory label $label found"
+              exit 0
+            fi
+          done
+          
+          echo "Error: None of the mandatory labels (${MANDATORY_LABELS[*]}) are present on this pull request."
+          exit 1
+
+  # Build the project after increment_version or release_version
+  build:
+    runs-on: ubuntu-latest
+    needs: release_version
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up JDK 21
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'temurin'
+          java-version: '21'
+
+      - name: Cache Maven packages
+        uses: actions/cache@v4
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
+
+      - name: Install dependencies
+        run: mvn install -DskipTests
+
+      - name: Run tests
+        run: mvn test
+
+      - name: Package the application
+        run: mvn package -DskipTests
+
+  release_version:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -22,27 +73,8 @@ jobs:
           distribution: 'temurin'
           java-version: '21'
 
-      # Increment SNAPSHOT VERSION on develop push
-      - name: Increment SNAPSHOT version
-        if: github.ref == 'refs/heads/develop'
-        run: |
-          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
-          BASE_VERSION=$(echo $CURRENT_VERSION | sed 's/-SNAPSHOT//')
-          IFS='.' read -ra ADDR <<< "$BASE_VERSION"
-          MAJOR=${ADDR[0]}
-          MINOR=${ADDR[1]}
-          PATCH=${ADDR[2]}
-          NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))-SNAPSHOT"
-          mvn versions:set -DnewVersion=$NEW_VERSION
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          git add pom.xml
-          git commit -m "Increment SNAPSHOT version to $NEW_VERSION"
-          git push origin develop
-
       # Increment version depending on release type on a pull request
       - name: Determine Release Version
-        if: github.event.pull_request.merged == true && github.ref == 'refs/heads/master'
         id: determine_version
         run: |
           LABELS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
@@ -82,7 +114,6 @@ jobs:
           echo "new_dev_version=$NEW_DEV_VERSION" >> $GITHUB_ENV
 
       - name: Perform release
-        if: github.event.pull_request.merged == true && github.ref == 'refs/heads/master'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
@@ -91,68 +122,9 @@ jobs:
           mvn --batch-mode release:prepare release:perform -DreleaseVersion=$NEW_VERSION -DdevelopmentVersion=$NEW_DEV_VERSION
           git push origin master --tags
 
-  # Build the project after increment_version or release_version
-  build:
-    runs-on: ubuntu-latest
-    needs: versioning
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up JDK 21
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '21'
-
-      - name: Cache Maven packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-maven-
-
-      - name: Install dependencies
-        run: mvn install -DskipTests
-
-      - name: Run tests
-        run: mvn test
-
-      - name: Package the application
-        run: mvn package -DskipTests
-
-  # Analyse SonarQube only for pushes on develop branch
-  sonarqube:
-    runs-on: ubuntu-latest
-    needs: build
-    if: github.ref == 'refs/heads/develop'
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up JDK 21
-        uses: actions/setup-java@v4
-        with:
-          distribution: 'temurin'
-          java-version: '21'
-
-      - name: SonarQube Scan
-        env:
-          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
-          SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
-        run: |
-          mvn sonar:sonar \
-          -Dsonar.projectKey=Torrents-Uploader-Web \
-          -Dsonar.host.url=${{ secrets.SONARQUBE_URL }} \
-          -Dsonar.token=${{ secrets.SONARQUBE_TOKEN }} \
-          -Dsonar.java.binaries=target
-
 #  docker:
 #    runs-on: ubuntu-latest
 #    needs: build
-#    if: github.ref == 'refs/heads/master'
 
 #    steps:
 #      - name: Checkout code
